# Generated by Django 3.2.7 on 2021-09-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_dashboardnavbar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardnavbar',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
