# Generated by Django 3.2.7 on 2021-09-18 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_dashboardnavbar_dashboardnavbaritems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DashboardNavbarItems',
            new_name='DashboardNavbarItem',
        ),
    ]
