# Generated by Django 3.2.7 on 2021-09-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_dashboardnavbaritems_dashboardnavbaritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/placeholder-img.png', null=True, upload_to=''),
        ),
    ]
